# Generated by Django 5.0.6 on 2024-07-10 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('IntegratedHealthCare', '0002_alter_patientsignup_mobile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patientsignup',
            name='password',
            field=models.CharField(max_length=16),
        ),
        migrations.AlterField(
            model_name='patientsignup',
            name='reenterpassword',
            field=models.CharField(max_length=16),
        ),
    ]
