# Generated by Django 5.0.6 on 2024-07-18 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('IntegratedHealthCare', '0002_adminsignup_doctorsignup_labtechniciansignup_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='patientsignup',
            name='profile_pic',
            field=models.ImageField(blank=True, null=True, upload_to='profile_pics/'),
        ),
    ]
