# Generated by Django 5.0.6 on 2024-07-13 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('IntegratedHealthCare', '0003_alter_patientsignup_password_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='doctorSignUp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('specialist', models.CharField(max_length=100)),
                ('hname', models.CharField(max_length=200)),
                ('gender', models.CharField(choices=[('male', 'Male'), ('female', 'Female')], max_length=6)),
                ('email', models.CharField(max_length=100)),
                ('mobile', models.CharField(max_length=10)),
                ('password', models.CharField(max_length=16)),
                ('reenterpassword', models.CharField(max_length=16)),
            ],
        ),
    ]
