# Generated by Django 5.0.7 on 2024-07-14 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('IntegratedHealthCare', '0004_doctorsignup'),
    ]

    operations = [
        migrations.CreateModel(
            name='receptionistSignUp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('hname', models.CharField(max_length=200)),
                ('gender', models.CharField(choices=[('male', 'Male'), ('female', 'Female')], max_length=6)),
                ('email', models.EmailField(max_length=100)),
                ('mobile', models.CharField(max_length=10)),
                ('address', models.CharField(max_length=200)),
                ('password', models.CharField(max_length=16)),
            ],
        ),
        migrations.RemoveField(
            model_name='doctorsignup',
            name='reenterpassword',
        ),
        migrations.RemoveField(
            model_name='patientsignup',
            name='reenterpassword',
        ),
        migrations.AlterField(
            model_name='doctorsignup',
            name='email',
            field=models.EmailField(max_length=254),
        ),
        migrations.AlterField(
            model_name='patientsignup',
            name='email',
            field=models.EmailField(max_length=254),
        ),
    ]
