# Generated by Django 5.0.7 on 2024-07-21 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('IntegratedHealthCare', '0005_timeslot'),
    ]

    operations = [
        migrations.AddField(
            model_name='timeslot',
            name='d_price',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
