# Generated by Django 5.0.7 on 2024-07-14 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('IntegratedHealthCare', '0005_receptionistsignup_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='labtechnicianSignUp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('age', models.IntegerField()),
                ('gender', models.CharField(choices=[('male', 'Male'), ('female', 'Female')], max_length=6)),
                ('email', models.EmailField(max_length=254)),
                ('mobile', models.CharField(max_length=10)),
                ('lname', models.CharField(max_length=200)),
                ('laddress', models.CharField(max_length=200)),
                ('password', models.CharField(max_length=16)),
            ],
        ),
    ]
