# Generated by Django 5.0.7 on 2024-07-14 12:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('IntegratedHealthCare', '0006_labtechniciansignup'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='labtechniciansignup',
            name='age',
        ),
    ]
